import os

ADDR_RUN_LANG_PY_HOST = os.environ.get("PYTHON_ENGINE_SERVICE_HOST")
ADDR_RUN_LANG_PY_PORT = os.environ.get("PYTHON_ENGINE_SERVICE_PORT")

ADDR_RUN_LANG_JS_HOST = os.environ.get("JS_ENGINE_SERVICE_HOST")
ADDR_RUN_LANG_JS_PORT = os.environ.get("JS_ENGINE_SERVICE_PORT")

ADDR_RUN_LANG_CPP_HOST = os.environ.get("CPP_ENGINE_SERVICE_HOST")
ADDR_RUN_LANG_CPP_PORT = os.environ.get("CPP_ENGINE_SERVICE_PORT")

ADDR_RUN_LANG_RUST_HOST = os.environ.get("RUST_ENGINE_SERVICE_HOST")
ADDR_RUN_LANG_RUST_PORT = os.environ.get("RUST_ENGINE_SERVICE_PORT")

RUN_LANG_TABLE = {
    "python": ADDR_RUN_LANG_PY_HOST + ":" + ADDR_RUN_LANG_PY_PORT,
    "javascript": ADDR_RUN_LANG_JS_HOST + ":" + ADDR_RUN_LANG_JS_PORT,
    "cpp": ADDR_RUN_LANG_CPP_HOST + ":" + ADDR_RUN_LANG_CPP_PORT,
    "rust": ADDR_RUN_LANG_RUST_HOST + ":" + ADDR_RUN_LANG_RUST_PORT,
}
