Resources:
  RedisCacheSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      CacheSubnetGroupName: redissubnetgroup
      Description: Subnets for Redis ElastiCache
      SubnetIds: 
        - !ImportValue PrivateSubnetID
        - !ImportValue PrivateSubnetBID

  RedisCacheReplicationGroup:
    DependsOn: RedisCacheSubnetGroup
    Type: AWS::ElastiCache::ReplicationGroup
    Properties: 
      AutomaticFailoverEnabled: true
      CacheNodeType: cache.t3.micro
      CacheParameterGroupName: default.redis6.x
      CacheSubnetGroupName: redissubnetgroup
      Engine: redis
      MultiAZEnabled: true
      NumCacheClusters: 2
      Port: 6379
      ReplicationGroupDescription: Replica group for redis cache cluster
      SecurityGroupIds: 
        - !ImportValue RedisCacheClusterSecurityGroupID
