Resources:
  AppCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: app-cluster
      KubernetesNetworkConfig:
        # Should NOT overlap with VPC CIDR
        ServiceIpv4Cidr: 192.168.0.0/16
      ResourcesVpcConfig:
        SecurityGroupIds: 
          - !ImportValue EKSWorkerNodeSecurityGroupID
        SubnetIds: 
          - !ImportValue PrivateSubnetID
          - !ImportValue PrivateSubnetBID
          - !ImportValue PublicSubnetAID
          - !ImportValue PublicSubnetBID
      RoleArn: arn:aws:iam::979926061731:role/eksClusterRole

  AppNodeGroup:
    DependsOn: AppCluster
    Type: AWS::EKS::Nodegroup
    Properties: 
      AmiType: AL2_x86_64
      ClusterName: app-cluster
      DiskSize: 20
      ForceUpdateEnabled: true
      InstanceTypes: 
        - t2.small
      NodeRole: arn:aws:iam::979926061731:role/NodeInstanceRole
      RemoteAccess: 
        Ec2SshKey: kevinayaz
        SourceSecurityGroups:
          - !ImportValue BastionHostSecurityGroupID
      ScalingConfig:
        DesiredSize: 2
        MaxSize: 3
        MinSize: 1
      Subnets: 
        - !ImportValue PrivateSubnetID
        - !ImportValue PrivateSubnetBID
