Resources:
  # TODO
  AppCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: app-cluster
      KubernetesNetworkConfig:
        # Should *not* overlap with VPC CIDR
        ServiceIpv4Cidr: 192.168.0.0/16
      ResourcesVpcConfig: 
        ResourcesVpcConfig
      RoleArn: String
  # TODO
