Resources:
  WebserverLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Subnets:
        - !ImportValue PublicSubnetAID
        - !ImportValue PublicSubnetBID

  BastionHost:
    Type: AWS::EC2::Instance
    Properties:
      # Ubuntu 18.04
      ImageId: ami-0e82959d4ed12de3f
      InstanceType: t3.small
      KeyName: kevinayaz
      SubnetId: !ImportValue PublicSubnetAID
      SecurityGroupIds:
        - !ImportValue BastionHostSecurityGroupID
      Tags:
        - Key: Name
          Value: bastion-host
