Resources:
  WebserverLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Subnets:
        - !ImportValue PublicSubnetAID
        - !ImportValue PublicSubnetBID

  BastionHost:
    Type: AWS::EC2::Instance
    Properties:
      # Ubuntu 18.04
      ImageId: ami-025102f49d03bec05
      InstanceType: t2.small
      KeyName: kevin
      SubnetId: !ImportValue PublicSubnetAID
      SecurityGroupIds:
        - !ImportValue BastionHostSecurityGroupID
      Tags:
        - Key: Name
          Value: bastion-host
