apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: python-engine
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: python-engine
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cpp-engine
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cpp-engine
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: js-engine
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: js-engine
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: rust-engine
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rust-engine
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: router
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: router
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
