apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: python-engine
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: python-engine
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 25
