apiVersion: v1
kind: Service
metadata:
  name: javascript-engine
spec:
  selector:
    app: javascript-engine
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: javascript-engine
  labels:
    app: javascript-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javascript-engine
  template:
    metadata:
      labels:
        app: javascript-engine
    spec:
      containers:
      - name: javascript-engine
        image: kevjin/runjavascript:latest
        # Ensures latest is always pulled from remote registry
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
