apiVersion: v1
kind: Service
metadata:
  name: python-engine
spec:
  selector:
    app: python-engine
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-engine
  labels:
    app: python-engine
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-engine
  template:
    metadata:
      labels:
        app: python-engine
    spec:
      containers:
      - name: python-engine
        image: kevjin/runpython:latest
        # Ensures latest is always pulled from remote registry.
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
