name: engine-docker-images
on:
  push:
    branches:
    - master
    paths:
    - 'images/**'

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      # - name: Builds and pushes all language engine images
      #   uses: PUSH=true ./build_images.sh
