name: k8s-cluster-deployment
on:
  push:
    branches:
    - master
    paths:
    - 'kubernetes/**'

jobs:
  apply-k8s-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name:
        run: |
          curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.19.0/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl
          kubectl version --client
      # - name: deploy to cluster
      #   uses: steebchen/kubectl@master
      #   env:
      #     KUBE_CONFIG_DATA: ${{ secrets.KUBECONFIG }}
      #   with:
      #     args: get svc
      - name: Applies all changed k8 manifest/config files.
        run: kubectl get svc
